#!/usr/bin/env bash
# Regenerates publish.css from theme.css. Swaps the top banner comment for
# a Publish-specific one, and drops the editor-only half of each paired
# selector (anything starting with .markdown-source-view.mod-cm6), since
# published pages have no editor or Live Preview. Everything else in
# theme.css, including the embedded font block, carries over unchanged,
# so the two files can no longer drift out of sync by hand.
#
# Run this after editing theme.css, or via scripts/build.sh to also
# regenerate the embedded font block first.
set -euo pipefail
cd "$(dirname "$0")/.."

SOURCE_CSS="theme.css"
TARGET_CSS="publish.css"

# theme.css must open with the banner comment as its very first line. This
# finds the first line ending in '*/' to know where that comment closes,
# instead of a hardcoded line count silently drifting out of sync with the
# actual comment.
banner_end_line="$(grep -n -m1 '\*/ *$' "$SOURCE_CSS" | cut -d: -f1)" || true
if [[ -z "$banner_end_line" ]]; then
  echo "error: could not find the closing '*/' of the banner comment at the top of $SOURCE_CSS" >&2
  exit 1
fi

banner="$(mktemp)"
trap 'rm -f "$banner"' EXIT
cat >"$banner" <<'EOF'
/* ┌───────────────────────────────────────────────────────────────────────┐
   │ obsidian-vitela - Obsidian Publish edition                            │
   │                                                                       │
   │ Generated by scripts/build-publish-css.sh from theme.css, do not      │
   │ edit by hand. Same theme, trimmed to the selectors that apply to a    │
   │ published site (no editor / Live Preview, since published pages are   │
   │ read-only rendered HTML).                                             │
   │                                                                       │
   │ Usage: copy this file to the root of the vault that Obsidian Publish  │
   │ serves, as 'publish.css'. Obsidian Publish picks it up automatically. │
   └───────────────────────────────────────────────────────────────────────┘ */
EOF

{
  cat "$banner"
  tail -n "+$((banner_end_line + 1))" "$SOURCE_CSS" | grep -v '\.markdown-source-view\.mod-cm6'
} >"$TARGET_CSS.tmp"
mv "$TARGET_CSS.tmp" "$TARGET_CSS"

echo "publish.css regenerated from $SOURCE_CSS"
