#!/usr/bin/env bash
# Regenerates the base64-embedded @font-face block in theme.css from the
# source files in fonts/. theme.css is the only file touched here, since
# publish.css is itself generated from theme.css by build-publish-css.sh,
# which carries the font block over in the same pass.
#
# Run this after adding, removing or replacing a file in fonts/, or via
# scripts/build.sh to also regenerate publish.css in the same step.
set -euo pipefail
cd "$(dirname "$0")/.."

FONTS_DIR="fonts"
THEME_CSS="theme.css"
BEGIN_MARKER="/* BEGIN GENERATED FONTS — generated by scripts/build-fonts.sh, do not edit by hand */"
END_MARKER="/* END GENERATED FONTS */"

# family|style|weight (or weight range for variable fonts)|source file
entries=(
  "Lora|normal|400 700|lora-roman.woff2"
  "Lora|italic|400 700|lora-italic.woff2"
  "EB Garamond|normal|400 800|eb-garamond-roman.woff2"
  "EB Garamond|italic|400 800|eb-garamond-italic.woff2"
  "IBM Plex Mono|normal|400|ibm-plex-mono-400.woff2"
  "IBM Plex Mono|normal|500|ibm-plex-mono-500.woff2"
  "IBM Plex Mono|normal|600|ibm-plex-mono-600.woff2"
  "IBM Plex Mono|normal|700|ibm-plex-mono-700.woff2"
  "IBM Plex Mono|italic|400|ibm-plex-mono-400-italic.woff2"
)

generated="$(mktemp)"
trap 'rm -f "$generated"' EXIT

echo "$BEGIN_MARKER" >>"$generated"
for entry in "${entries[@]}"; do
  IFS="|" read -r family style weight file <<<"$entry"
  path="$FONTS_DIR/$file"
  if [[ ! -f "$path" ]]; then
    echo "error: $path not found" >&2
    exit 1
  fi
  b64="$(base64 "$path" | tr -d '\n')"
  {
    echo "@font-face {"
    echo "  font-family: \"$family\";"
    echo "  font-style: $style;"
    echo "  font-weight: $weight;"
    echo "  font-display: swap;"
    echo "  src: url(data:font/woff2;base64,$b64) format(\"woff2\");"
    echo "}"
    echo
  } >>"$generated"
done
echo "$END_MARKER" >>"$generated"

awk -v beginm="$BEGIN_MARKER" -v endm="$END_MARKER" -v genfile="$generated" '
  $0 == beginm { while ((getline line < genfile) > 0) print line; close(genfile); skip=1; next }
  $0 == endm   { skip=0; next }
  skip         { next }
  { print }
' "$THEME_CSS" >"$THEME_CSS.tmp"
mv "$THEME_CSS.tmp" "$THEME_CSS"

echo "theme.css fonts regenerated from $FONTS_DIR/"
